# Generated by Django 2.2.9 on 2020-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200302_1458'),
        ('books', '0002_auto_20200227_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='books', to='clubs.Club'),
        ),
    ]
