# Generated by Django 2.2.9 on 2020-03-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20200304_1200'),
        ('jwt_auth', '0004_auto_20200305_1507'),
    ]

    operations = [
    ]
