# Generated by Django 2.2.9 on 2020-03-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_merge_20200308_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
