# Generated by Django 2.2.9 on 2020-02-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('maxspace', models.CharField(max_length=50)),
                ('books', models.ManyToManyField(blank=True, to='books.Book')),
            ],
        ),
    ]
