# Generated by Django 2.2.9 on 2020-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20200227_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='_club_book_+', to='books.Book'),
        ),
    ]
